### ISSUE TITLE
好像不能用呀。

### ISSUE THREAD

**Issue by pengwj** [netyouli/WHC_ScanUnreferenceImageTool#1]
进度走到最后就走不动了，而且我用二进制比对工具比对后发现跟之前备份的文件没有任何差别

**Comment by netyouli** [comment]
少出来的图片需要手动去删除

**Comment by pengwj** [comment]
那好吧。汗...

发自我的 iPhone

**Comment by netyouli** [comment]
为了防止勿删，所以没有加自动删去，呵呵要是勿删了你不得骂我吗

**Comment by NashLegend** [comment]
其实Android Studio已经自带删除无用资源的功能了 0.0 。Refactor => remove unused resources

**Comment by rjliulei** [comment]
windows怎么用啊？你可以加一个删除按钮，想删就删，不删就不点
