### ISSUE TITLE
Not support Xib,storyboard

### ISSUE THREAD

**Issue by foxsin10** [netyouli/WHC_ScanUnreferenceImageTool#3]
when it works,can't scan the images used in Xib,Storyboard

**Comment by netyouli** [comment]
支持的

**Comment by foxsin10** [comment]
嗯，仔细看了代码是支持的，但是一般图片会有带@2x，@3x后缀适配不同机型。现在暂时只检查图片的主要名称，所以。。

**Comment by netyouli** [comment]
就是检查@前面的名称，因为我使用图片的时候并不会带上@2，或者@3.

**Comment by foxsin10** [comment]
嗯，自己改了，感谢分享
