### ISSUE TITLE
删除图片之后再次扫描结果没变

### ISSUE THREAD

**Issue by KFAaron** [netyouli/WHC_ScanUnreferenceImageTool#5]
第一次扫描出来的图确实没用，都一一删除了，这点谢谢作者！不然一个一个找很麻烦。但是有个问题，我把图片删了之后再次扫描竟然还是一样的结果，另外对于icon的图标的处理感觉不是很准~

**Comment by netyouli** [comment]
应该不会删除了之后还会扫出来，这个是扫出来之后需要手工删除并不会自动删除，还或者是第二次扫描第一次的扫出的内容没有清空，这个也会不断改进
