### ISSUE TITLE
如果图片命名和assets里的图片命名不一致，扫描不出来

### ISSUE THREAD

**Issue by shaveKevin** [netyouli/WHC_ScanUnreferenceImageTool#7]
<img width="800" alt="2016-12-19 08 40 42" src="https://cloud.githubusercontent.com/assets/9313522/21298118/1169c0e0-c5c7-11e6-952f-e41d41d027de.png">
  还有如果图片的使用方式不是imagenamed  而是采用 数组的形式的话 也扫描不出来

**Comment by netyouli** [comment]
只要是字符串数组是可以的，assets里面名称和图片文件名称不一样目前是确实是不准确，以后在考虑优化，这个扫出来的结果是需要自己手动核对一遍再决定是否真正没有引用然后再考虑删除图片的

**Comment by shaveKevin** [comment]
采用for循环 取图片也不行吧 比如说image_01.jpg   image_02.jpg  image_%ld

**Comment by netyouli** [comment]
对，但这不是重点，因为还需要你自己手动去核对一遍然后再决定是否删除图片

**Comment by shaveKevin** [comment]
got  it
