### ISSUE TITLE
iOS 在xib中直接使用的图片也扫描不出来，有些被扫描出来的图片在我本地用了，但还是被扫描出来。大多数都正确。

### ISSUE THREAD

**Issue by asd8855** [netyouli/WHC_ScanUnreferenceImageTool#8]

**Comment by asd8855** [comment]
[UIImage imageNamed:@"icon_activevalue_already_signin"]  icon_activevalue_already_signin这个图片我用到了但还是被扫出来

**Comment by netyouli** [comment]
[UIImage imageNamed:@"icon_activevalue_already_signin"]这个是可以扫出来的，很可能你扫描的目录里没这个图片，你最好从项目根目录扫描，这样不会漏图片，上次有哥们也是

**Comment by asd8855** [comment]
哦哦谢谢了
